openapi: 3.1.0
info:
  title: Rock Paper Scissors Game API
  version: 0.0.1

components:
  schemas:
    HashAlg:
      type: string
      enum: [
        'sha512', 'sha512_256', 'sha384', 'sm3', 'blake2s',
        'sha3_512', 'sha512_224', 'sha3_384', 'shake_128',
        'md5-sha1', 'sha1', 'ripemd160', 'md5', 'sha3_256',
        'sha224', 'shake_256', 'blake2b', 'sha3_224', 'sha256'
      ]
    Hash:
      type: object
      properties:
        algorithm:
          $ref: '#/components/schemas/HashAlg'
        hash:
          type: string
          minLength: 30
          maxLength: 2000
    Client:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        supportedExtensions:
          type: array
          items:
            type: string
        supportedHashingAlgorithms:
          type: array
          items:
            $ref: '#/components/schemas/HashAlg'
    Message:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/MessageType'
        publicKey:
          type: string
        datetime:
          type: string
          format: date-time
        uuid:
          type: string
          format: uuid
        re:
          oneOf:
            - $ref: '#/components/schemas/MessageRef'
            - type: 'null'
    MessageRef:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        hash:
          $ref: '#/components/schemas/Hash'
    MessageType:
      type: string
      enum:
        - init
        - ack
    RoundsInfo:
      type: object
      properties:
        type:
          type: string
          enum:
            - firstToXWins
            - XRounds
            - XRoundsIncludingTies
        X:
          type: integer
paths:
  /start:
    post:
      summary: Start a game of rock paper scissors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              allOf:
                - $ref: '#/components/schemas/Message'
              properties:
                type:
                  type: string
                  enum:
                    - init
                url:
                  type: string
                  format: uri
                roundsInfo:
                  $ref: '#/components/schemas/RoundsInfo'
                symbols:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      winsAgainst:
                        type: array
                        items:
                          type: string
                      losesAgainst:
                        type: array
                        items:
                          type: string
                      canBeDisabled:
                        type: boolean
                        default: false
                      isEnabledByDefault:
                        type: boolean
                        default: true
                      resetsToDefaultAfterEveryMove:
                        type: boolean
                        default: false
                client:
                  type: object
                  $ref: '#/components/schemas/Client'
